name: CI/CD

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ dev, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Simular build
        run: |
          mkdir output
          echo "Build em $(date)" > output/build.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: output/

  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Logar no DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build da imagem
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/minha-aplicacao:latest .

      - name: Push da imagem para o DockerHub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/minha-aplicacao:latest

  deploy:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: ./deploy

      - name: Simular deploy
        run: |
          echo "Deploy rodando com artifact e imagem do DockerHub!"
          ls -l ./deploy
          cat ./deploy/build.txt
