name: BUILD

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Simular build
        run: |
          mkdir output
          echo "Arquivo gerado no build em $(date)" > output/build.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: output/
