name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run tests
        run: echo "teste integração"
